build:
  cuda_version: "12.1.1"
  system_packages:
    - "libssl-dev"
    - "libx11-6"
    - "libxext6"
    - "libgl1-mesa-glx"
  python_packages:
    - "torch==2.3.1"
    - "diffusers==0.28.2"
    - "transformers==4.41.2"
    - "accelerate==0.30.1"
